### ISSUE TITLE
Site Responsiveness

### ISSUE THREAD

**Issue by evanjscallan** [orcasound/orcahome#10]
I'd like to work on making the page more flexible in regards to the overall responsiveness of the page. Implementations would include:

-Switching elements to primarily relative units (em, rem, vh, %, etc.) so that they may scale accordingly.
-Utilizing flex for alignment of elements.
-Pre-loading the most important elements of the page first.
-Reducing redundancies across the site.

Would love to hear your thoughts.

**Comment by paulcretu** [comment]
These are really good, fully agree. There are actually [proposed designs for the website](https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290), both desktop and mobile views (we should probably link this somewhere in this repo).

For implementation, I highly recommend using a CSS framework to do some of the heavy lifting (e.g. calculate the px/em/rem for you at specific breakpoints/scales for consistent sizing). @imacchiavello started by mostly using Bootstrap 4 in this project to get up and running quickly. At this point though, my preference would be to switch to Material-UI/MUI for consistency since it's what we're using over in the orcasite repo and the more we build with Bootstrap the harder it'll be to switch later. MUI comes with some [pretty good tools](https://mui.com/guides/responsive-ui/) for building responsive pages.

For dealing with units, MUI has a [spacing scale](https://mui.com/customization/spacing/) and [utility](https://mui.com/system/spacing/) that abstracts away the actual values and keeps things consistent. Combined with theme [breakpoints](https://mui.com/system/basics/#responsive-values) and [Grid](https://mui.com/components/grid/#grid-with-multiple-breakpoints), it's super easy to render different sized elements based on screen size.

Flex is great for one dimensional layouts, and CSS grid for two dimensions.

Pre-loading is handled by Next.js, which can generate [static pages at compile-time](https://nextjs.org/docs/basic-features/pages#static-generation-recommended) (SSG). Technically this isn't really even pre-loading, it bypasses the need to pre-load altogether (still need to think about images, but Next has a [good util](https://nextjs.org/docs/api-reference/next/image) for that too). Next.js will also by default pre-fetch linked pages after loading the current page.

For redundancies, it would be nice to turn commonly used sections of the page into components (e.g. nav bar), and I'm hoping to be able to share them between orcahome and orcasite… somehow. Still need to figure that out. For now I think it'll be interesting to see how each project goes and compare once we have a few components.

**Comment by MohitSharma-21** [comment]
I would like to work on this issue, any guidance will be very great.

**Comment by rodrickcalvin** [comment]
Assign me the task for the redesign I can take it up. With your guidance

**Comment by paulcretu** [comment]
These are great guiding principles. This issue probably isn't actionable enough given that none of the pages are finished yet. When implementing each page, devs should keep responsiveness in mind. Going to close this one out and we can make new issues if there are specific tweaks that need to be made.
